<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
    <PlatformTarget Condition="'$(Platform)' == 'x86'">x86</PlatformTarget>
    <PlatformTarget Condition="'$(Platform)' != 'x86'">x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Drawing" />
    <ProjectReference Include="../Smiles2Img.csproj" />
    <PackageReference Include="Indigo.Net" Version="1.48.0-rc.1" GeneratePathProperty="true" />
  </ItemGroup>
  <Target Name="CopyNativeLibraries" AfterTargets="Build">
    <PropertyGroup>
      <NativeArchitecture Condition="'$(Platform)' == 'x86'">x86</NativeArchitecture>
      <NativeArchitecture Condition="'$(Platform)' != 'x86'">x64</NativeArchitecture>
    </PropertyGroup>
    <ItemGroup>
      <NativeFiles Include="$(PkgIndigo_Net)/runtimes/win-$(NativeArchitecture)/native/*.dll"
          Exclude="$(PkgIndigo_Net)/runtimes/win-x86/native/vcruntime140_1.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(NativeFiles)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
